### ISSUE TITLE
Ofgwrite and rootfs archive types

### ISSUE THREAD

**Issue by mihaip1948** [oe-alliance/ofgwrite#19]
Hi Betacentauri 

- it will be a good idea to add thru archive types .tar.xz
witch is used by all DreamOS like images
- you can build autoexec.img from user provided parts : 
kernel.img , rootfs.tar.** and bootlogo.bmp

User will provide a SD card formatted as : 32 Mb Fat16 and 1 Gb Ext4 partitions

**Comment by betacentauri** [comment]
Ofgwrite now also supports rootfs.tar.xz files:
https://github.com/oe-alliance/ofgwrite/commit/87e84ea96a8417f7e10687696ef1950c4a859ed3

**Comment by mihaip1948** [comment]
wow ! excelent ! thanks !
    Pe sâmbătă, 27 mai 2023 la 13:17:47 EEST, Betacentauri ***@***.***> a scris:  
 
 


Closed #19 as completed.
