### ISSUE TITLE
Error flashing Zgemma H8

### ISSUE THREAD

**Issue by NokiasSOFT** [oe-alliance/ofgwrite#26]
Can you please add support for the Zgemma h8 receiver?
In this equipment, the flashing process always goes wrong and it is necessary to flash via USB to recover it.

I noticed that Captain made a correction to be compatible with the new H17. At this moment I didn't have the opportunity to test whether it also solved the problem on the H8.
Thanks!

**Comment by atvcaptain** [comment]
please check next image, i have fix image download and flashonline

**Comment by NokiasSOFT** [comment]
Thanks for the answer.
I didn't quite understand what you said in relation to having fixed the image and flashrecovery, but the problem I'm specifically referring to is flashing the image manually through the shell using ofgwrite.

I've been checking the commits and the last fix that appears in relation to ofgwrite is h17.

**Comment by FredericoLacerda** [comment]
I have the same problem with H8 could you please support ?

**Comment by atvcaptain** [comment]
h17 have emmc and h8 nand the commit for h17 have nothing todo with h8
flash h82h woks here without any issue 
send a long file with your issue
