### ISSUE TITLE
Zgemma h7 and h9 no image/progress screen during flash

### ISSUE THREAD

**Issue by NokiasSOFT** [oe-alliance/ofgwrite#6]
When using the ofgwrite on the zgemma h7 and h9 (4k arm) I noticed it is not shown
the progress screen. Instead the signal sent to the hdmi is turned off
completely as if the equipment were to power off.

Sometimes you can see the boot show's "showframe" and the progress screen,
but quickly the equipment turns off the video output, being no more possible to follow the flash progress.

I do not know if it happens also in other 4k (arm) receivers.

**Comment by NokiasSOFT** [comment]
https://github.com/oe-alliance/ofgwrite/commit/e6966a4d59826e04912802f43dfa4c9b9abff18c
Isn't it possible to do something like this?

Is it mandatory to close the process / service / driver responsible for the video output to the hdmi, so that it can flash the receiver ??

**Comment by betacentauri** [comment]
No, it's an other issue.

**Comment by betacentauri** [comment]
Should be fixed in latest version.
As driver devs didn't fix I added a workaround.
