### ISSUE TITLE
Fehler?

### ISSUE THREAD

**Issue by kueken** [oe-alliance/ofgwrite#7]
```
umounting: /media
umounting: /sys/kernel/debug
umounting: /
sh: /bin/automount: not found
Error starting autofs
Execute: fuser -k -m /oldroot/
1 2 3 4 5 6 11 12 206 208 210 216 217 221 226 229 249 254 255 256 257 258 259 262 263 264 265 915 921 1094 1095 1169 1192 1201 1220 1224 1225 1226 1272 1273 1364 1393 1477 1478 1492 1602 1841 1851 1945 1946
umount not successful
Error remounting root! Abort flashing.

```

**Comment by betacentauri** [comment]
Thanks. There are similar reports in OpenATV forum. I will look into it, but unfortunately not before Sunday as I currently have no access to a receiver and PC.

**Comment by betacentauri** [comment]
Liegt an diesem Commit
https://github.com/oe-alliance/ofgwrite/commit/d5d5666291c5afa5e12a18702917d68ff29b9185
Ist bei dir auch die Festplatte bzw der USB Stick auf dem die Image Dateien liegen 2x mal gemountet? Schau mal in die Ausgabe von mount.

**Comment by kueken** [comment]
ich kann da nur ein mount feststellen.

**Comment by kueken** [comment]
Ich glaub da passiert genau das, was nicht passieren soll.
Netzwerkmounts und andere zusätzliche außer HDD/ImageHDD werden nicht getrennt und führen zu dem Fehler.
Willst du es nicht erst mal reverten?
Ist ja nicht so einfach lokal zu reparieren. Es gibt schon ein paar Boxen die mangels Speicher das Onlineflash/lokal brauchen.

**Comment by atvcaptain** [comment]
im Auftrag von betacentauri erstmal revert alles, bis er wieder zurück ist

**Comment by kueken** [comment]
ok, dann mach ich mal zu.
Grüße
