### ISSUE TITLE
hd51 new flash with rootfssubdir broken

### ISSUE THREAD

**Issue by atvcaptain** [oe-alliance/ofgwrite#8]
ofgwrite Utility v4.4.1
Author: Betacentauri
Based upon: mtd-utils-native-1.5.1 and busybox 1.24.1
Use at your own risk! Make always a backup before use!
Don't use it if you use multiple ubi volumes in ubi layer!

Flashing rootfs
Flashing kernel
Flashing multiboot partition 2
Searching image files in /media/hdd/images/tmp resolved to /media/hdd/images/tmp
Found kernel file: /media/hdd/images/tmp/kernel.bin
Found rootfs file: /media/hdd/images/tmp/rootfs.tar.bz2
Found EXT4 rootfs
Found mounted /newroot
Found mounted /newroot
Found mounted /newroot
Found mountpoint for rootfs file: /media/hdd

Read /proc/cmdline
Current rootfs is: /dev/mmcblk0p3
Current kernel is: /dev/mmcblk0p2
Current root sub dir is: linuxrootfs1

Execute: fdisk -l
Found valid GPT with protective MBR; using GPT

Error: No kernel device found!
root@mutant51:~#

Okay, ich habe eine Benachrichtigung an betacentauri gesendet.

root@mutant51:~# /usr/bin/ofgwrite -f -r -k -m2 /media/hdd/images/tmp
so gestartet
root@mutant51:~# cat /proc/cmdline
brcm_cma=440M@328M brcm_cma=192M@768M root=/dev/mmcblk0p3 rootsubdir=linuxrootfs1 kernel=/dev/mmcblk0p2 rw rootwait hd51_4.boxmode=1 brcm_cma=440M@328M brcm_cma=192M@768M console=ttyS0,115200

**Comment by atvcaptain** [comment]
/dev/mmcblk0: PTUUID="be983b3a-51d0-4b67-8c81-3b86be97b91f" PTTYPE="gpt"
/dev/mmcblk0p2: PARTLABEL="linuxkernel" PARTUUID="440bd195-6370-48a7-b92a-e6cf6b3225e6"
/dev/mmcblk0p4: PARTLABEL="linuxkernel2" PARTUUID="db15ec37-699e-4dbb-ad65-17bc2b9287a6"
/dev/mmcblk0p5: PARTLABEL="linuxkernel3" PARTUUID="661866e3-1200-49bb-a90e-b6e8d99703b2"
/dev/mmcblk0p6: PARTLABEL="linuxkernel4" PARTUUID="97670682-3987-4019-9117-929923fcdf68"

**Comment by atvcaptain** [comment]
rootfs wird auch nicht gefunden

**Comment by betacentauri** [comment]
Fixed with https://github.com/oe-alliance/ofgwrite/commit/e7549be10fcc6f846eb523f0d8d615bb636e4a58
